version: '3.8'

services:
    simple-cron-scheduler:
        build: .
        container_name: simple-cron-scheduler
        environment:
            TZ: 'America/Argentina/Buenos_Aires'
            CRON: '* * * * *'
            PUID: 1000
            PGID: 1000